import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
    baseDirectory: __dirname,
});

const eslintConfig = [
    ...compat.extends('next/core-web-vitals', 'next/typescript'),
    {
        // next-env.d.ts is generated by Next and must not be edited; since 15.5
        // it includes a triple-slash path reference the TS rules reject.
        ignores: ['node_modules/*', '**/.*', 'archive/*', 'next-env.d.ts'],
    },
    {
        // These components render email HTML, where next/image can't work.
        files: ['src/app/(components)/**'],
        rules: { '@next/next/no-img-element': 'off' },
    },
    {
        // Editions are mostly prose, so allow typing ' and " directly instead of
        // &apos; and &quot;. React escapes them in the rendered HTML either way.
        files: ['src/app/(email-content)/**'],
        rules: { 'react/no-unescaped-entities': 'off' },
    },
];

export default eslintConfig;
